<a href="https://colab.research.google.com/github/SandraBakhita/My-name-/blob/main/mathassignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
matrixA= np.random.randint(1, 10, (2, 3)) #generating random matrices
print(matrixA)

[[5 5 8]
 [6 3 2]]


In [4]:
data_type = matrixA.dtype #data type
mean_value = np.mean(matrixA) #mean
median_value = np.median(matrixA) #median
print("Data Type:", data_type)
print("Mean:", mean_value)
print("Median:", median_value)

Data Type: int64
Mean: 4.833333333333333
Median: 5.0


In [5]:
matrixB=np.random.randint(1,20,(2,3))
print(matrixB)

[[ 5 14 14]
 [ 3 13 10]]


In [6]:
print(matrixA+matrixB) #addition

[[10 19 22]
 [ 9 16 12]]


In [7]:
print(matrixA*2) # multiplication

[[10 10 16]
 [12  6  4]]


In [8]:
print(matrixA*matrixB)

[[ 25  70 112]
 [ 18  39  20]]


In [9]:
print(matrixA.T) #transpose


[[5 6]
 [5 3]
 [8 2]]


In [10]:
print(matrixB.T)

[[ 5  3]
 [14 13]
 [14 10]]


In [11]:
print(matrixA-matrixB) #subtraction

[[  0  -9  -6]
 [  3 -10  -8]]



**Research and find a real-world application of matrices in data analysis and explain how it is used.**
Computer Graphics and Gaming:

Matrices are fundamental in computer graphics and gaming to represent 3D models. They facilitate operations such as scaling, rotation, and translation, as well as contribute to lighting and shading effects.